name: Build & Test

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Configure JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: 'gradle'
      - name: RunAllTests
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PRIVATE_KEY_PASSWORD: ${{ secrets.GPG_PRIVATE_KEY_PASSWORD }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        run: ./gradlew build publishToMavenLocal
      - name: Upload Linux Executables
        uses: actions/upload-artifact@v4
        with:
          name: executables-linux
          path: build/bin/linux*/releaseExecutable/*exe
          if-no-files-found: ignore
          overwrite: true
      - name: Upload Windows Executables
        uses: actions/upload-artifact@v4
        with:
          name: executables-windows
          path: build/bin/mingw*/releaseExecutable/*exe
          if-no-files-found: ignore
          overwrite: true
      - name: Upload MacOS Executables
        uses: actions/upload-artifact@v4
        with:
          name: executables-macos
          path: build/bin/macos*/releaseExecutable/*exe
          if-no-files-found: ignore
          overwrite: true
