name: Build & Test

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Configure JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: 'gradle'
      - name: BuildAndPublish
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PRIVATE_KEY_PASSWORD: ${{ secrets.GPG_PRIVATE_KEY_PASSWORD }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        run: |
          VERSION=1.1.0-RC.2.SNAPSHOT
          gradle -Pversion=$VERSION build publish
      - name: Github Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          prerelease: true
          name: 1.1.0-RC.2.SNAPSHOT
          files: |
            LICENSE
            build/distributions/*
            build/libs/*
